language: python
dist: bionic
group: stable
os: linux
python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8
before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install python3.5 python3.6 python3.7 python3.8
install: pip install tox coveralls
script: tox
after_success:
    - coveralls
